### PR TITLE
Serialize unit variants as name only

### PR DESCRIPTION
**Pull request by dtolnay**
Ref https://github.com/serde-rs/serde/issues/251. This is a rebase of #37 with more tests to ensure backward-compatibility with the current format.

### CODE REVIEW

**Comment by dtolnay** [comment]
@erickt I know you were previously against #37 but based on the discussion in https://github.com/serde-rs/serde/issues/251 I think this is the right solution.

I haven't seen a compelling argument that `{"A": []}` is the correct way to format an unit variant.

Serde_codegen is doing the right thing by calling `serialize_unit_variant`, and `serde_json` is doing the wrong thing by having chosen a surprising and unhelpful format for unit variants.

**Comment by dtolnay** [comment]
Rebased to fix the merge conflict with #80.

**Comment by dtolnay** [comment]
Ping @erickt

**Comment by dtolnay** [comment]
Erick's feedback on IRC was:

> I wonder if some of this logic should be moved into serde proper to avoid these runtime checks

**Comment by dtolnay** [comment]
@erickt I removed the runtime checks by using two different VariantVisitor implementations.

**Comment by erickt** [comment]
@homu: r+ f48e8d6

@dtolnay: looks great!

**Pull request merged**
