### PR TITLE
New Serializer API

### PR DESCRIPTION
**Pull request by dtolnay**
Update for serde-rs/serde#437.

### CODE REVIEW

**Comment by dtolnay** [comment]
@erickt @oli-obk this is about 5-15% improvement in serialization speed.

**Comment by erickt** [comment]
Wow! I didn't expect it to be that significant. At this point might actually have the fastest json serializer. @dtolnay: how's the json benchmarks repo? Are you still working on it? If we can demonstratively show we are winning in most cases we should write this up and publicize it.

**Comment by dtolnay** [comment]
`json-rust` is faster on some inputs - see the latest numbers [in this commit](https://github.com/serde-rs/json-benchmark/blob/5334dfbe50b9e366e525707c945c1495d2c8ccb0/README.md#-cargo-run---release). And it is much faster on small inputs.

**Comment by oli-obk** [comment]
Awesome

**Comment by arthurprs** [comment]
Great work!

**Pull request merged**
