### PR TITLE
Don't allow control characters in strings

### PR DESCRIPTION
**Pull request by maciejhirsz**
#90

### CODE REVIEW

**Comment by dtolnay** [comment]
Thanks! I'll take a look after work unless @oli-obk gets to it first.

**Comment by oli-obk** [comment]
Logic wise this is good. Since the array is only used in a boolean manner, we might consider doing a bitmask check on two `u64`s instead of indexing an array, but let's leave that to benchmarking.

It needs a few regression tests for some of the situations it's catching now.

**Comment by dtolnay** [comment]
According to [RFC7159](https://tools.ietf.org/html/rfc7159):

> All Unicode characters may be placed within the quotation marks, except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

Based on this language, I would consider it incorrect to reject `\x7F` in a string.

**Comment by maciejhirsz** [comment]
Will look into it after work, thanks!

**Comment by dtolnay** [comment]
I folded this into #100.

**Pull request closed without merging**
