### PR TITLE
Forward `InvalidType` and `InvalidLength` errors and remove the redundant `Error` suffix.

### PR DESCRIPTION
**Pull request by tomprogrammer**
This change is necessary if https://github.com/serde-rs/serde/pull/166 is merged. More information in the linked PR.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f69e7b21cee04e25586b9233c4bfcabf426af0c2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/json

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: da7ae95a7d0c296dfb41dc2a05cb87d8432d579b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c07920f9d39aaae421a80397bdb4b462db71d854
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 45d87f74e7c535e53336af1d2313bb462ad7e513
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c8cd1b947ff6fe368a3153c208b2e0bf601100db
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: aea44fce0632447611461075605f2a41f6efe3e4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/json

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8798f87980e97fcede8bddc3e1cad1bfda2e6d5f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fbb7d9ffb83447efe7637c12558ea36e099e8688
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6e4dcd7050b22bfb2f4271a8ff2bda19d573690a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/serde-rs/json

---
This message was auto-generated by https://gitcop.com

**Comment by tomprogrammer** [comment]
This PR builds and tests successfully against https://github.com/serde-rs/serde/tree/27c933a86548601027fc68bb7daf8082de819c10.

**Comment by erickt** [comment]
This has actually landed since serde 0.7 was released!

**Pull request closed without merging**
