### PR TITLE
Fix #256: support deserializing strings with arbitrary bytes

### LINKED ISSUE #256: Support deserializing arbitrary bytes inside strings
I know that it's not correct according to the JSON standard, but sometimes you get to deal with json that has arbitrary bytes inside a string literal (except '"'). To accomodate this use case, I suggest that we explictly implement the following two functions for the Deserializer:

* deserialize_bytes
* deserialize_byte_buf

to parse Strings without doing any processing on them, just returning the bytes. They can then be used to explictly request that one wants to parse a "raw" string.

### PR DESCRIPTION
**Pull request by bennofs**
Usecase described in #256. Also see the included documentation.

### CODE REVIEW

**Comment by dtolnay** [comment]
I misinterpreted "without doing any processing" in your proposal - I was thinking processing as in performing UTF-8 validation. Without interpreting escape sequences, this is a breaking change because the string containing backslash+n used to deserialize as one byte and now it deserializes as two bytes. Would this still be useful to you if we interpret escape sequences but just don't do the final from_utf8 conversion?

**Comment by bennofs** [comment]
OK, that works for my usecase as well. I thought that it might be a good idea to go all the way and allow the user to request access to the low level bytes, but I was not aware that other functionality uses visit_bytes already.

**Comment by bennofs** [comment]
@dtolnay changed it to only skip unicode validation and to allow delegate to `deserialize`.

**Comment by dtolnay** [comment]
Thanks, I released this in serde_json 0.9.7.

**Pull request merged**
