### PR TITLE
feat(value): impl Display and FromStr traits

### PR DESCRIPTION
**Pull request by s-panferov**
Refs #62 

I can add some tests, but implementation seems trivial. Tests fail on `nightly`, but this seems unrelated.

### CODE REVIEW

**Comment by erickt** [comment]
@homu: r+ bc78fe9

**Comment by erickt** [comment]
@s-panferov: Thanks that looks useful!

**Comment by oli-obk** [comment]
just a clippy failure

@bors retry

**Comment by oli-obk** [comment]
just a clippy failure

@homu retry

**Pull request merged**
