### PR TITLE
Speed up integer and float printing

### LINKED ISSUE #84: serialize_u64 is slow
It currently looks like this:

```rust
fn serialize_u64(&mut self, value: u64) -> Result<()> {
    write!(&mut self.writer, "{}", value).map_err(From::from)
}
```

I tested the following variation and it made an astonishing 20% difference in the [bench_log](https://github.com/serde-rs/json/blob/57739801bf53793062c84c5f144d07ce2f126a5d/json_tests/benches/bench_log.rs) benchmarks (294 MB/s vs 244 MB/s).

```rust
if value == 0 {
    self.writer.write_all(b"0").map_err(From::from)
} else {
    let mut scratch = [0u8; 20];
    let mut len = 0;
    while value > 0 {
        scratch[19 - len] = (value % 10) as u8 + b'0';
        value /= 10;
        len += 1;
    }
    self.writer.write_all(&scratch[20-len..20]).map_err(From::from)
}
```

That is enough to motivate looking for a better solution, or contributing a fix to Rust for whatever is making `write!` slow.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #84.

### CODE REVIEW

**Comment by oli-obk** [comment]
So if I understand your [implementation](https://github.com/dtolnay/itoa/blob/master/src/lib.rs) correctly, the only difference is that the original formatting implementation wrote to a temp buffer and then wrote to the target with an optional padding, while your implementation skips the padding and writes directly. Does llvm optimize the buffer away or what's the reason `itoa` is as fast as the direct impl you wrote in the issue?

r=me if there's no reason to rewrite `itoa` to directly write to the target.

**Comment by oli-obk** [comment]
I also wonder if it were possible to fix the original impl in Rust to be as fast as your version by adding a conditional check for whether going through the padding function is necessary.

**Comment by dtolnay** [comment]
> Does llvm optimize the buffer away or could it be optimized even more by writing directly?

It cannot write directly because it writes [backwards, least significant digit first](https://github.com/dtolnay/itoa/blob/01cb34a686a66269490f8b95acf16d3504a35ad6/src/lib.rs#L56).

> So if I understand your implementation correctly, the only difference is that the original formatting implementation wrote to a temp buffer and then wrote to the target with an optional padding, while your implementation skips the padding and writes directly.

They both write to a (stack-allocated) temp buffer. The only difference is that theirs [does all this stuff](https://github.com/rust-lang/rust/blob/b8214dc6c6fc20d0a660fb5700dca9ebf51ebe89/src/libcore/fmt/mod.rs#L906-L966) and mine doesn't.

> I also wonder if it were possible to fix the original impl in Rust to be as fast as your version by adding a conditional check for whether going through the padding function is necessary.

I filed https://github.com/dtolnay/itoa/issues/1 to follow up.

**Comment by dtolnay** [comment]
I added a similar library for printing floats. Note that the new library adds ".0" onto floats that are whole numbers, so we get "3.0" instead of "3". Let me know if you find this disagreeable, although RapidJSON and Jackson both write "3.0".

**Comment by dtolnay** [comment]
Also the new library writes `1.7976931348623157e308` instead of 179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 which seems like a good thing.

**Comment by oli-obk** [comment]
> Note that the new library adds ".0" onto floats that are whole numbers, so we get "3.0" instead of "3". Let me know if you find this disagreeable, although RapidJSON and Jackson both write "3.0".

I have no particular opinion on that. We might be breaking people's unit tests, but it's perfectly valid json to add arbitrary zeros.

> which seems like a good thing.

yes, definitely

lgtm, but I think we should hold off with such a user-visible change and do it together with 0.8

**Pull request closed without merging**
