### PR TITLE
Simplify creation of custom formatters with different escaping

### PR DESCRIPTION
**Pull request by andy128k**
Related to #537

### CODE REVIEW

**Comment by andy128k** [comment]
@dtolnay Could you give a feedback on this PR?

**Review by dtolnay — COMMENTED** [review]
Do you have a need for this other than the HtmlSafe case, or is it intended mostly for that? (I'm not sure if the EscapeAllCharactersFormatter is a use case you've come across in practice.)

**Comment by andy128k** [comment]
@dtolnay Practically only HtmlSafe is needed. Other examples are done only to have a test coverage and demonstrate flexibility.

**Review by dtolnay — COMMENTED** [review]
In that case I would prefer not to add this API -- all it accomplishes is makes HtmlSafe *slightly* fewer lines to implement. Comparing with vs without, I don't think the difference is significant enough to motivate this change.

```rust
impl Formatter for HtmlSafeCompactFormatter {
    fn char_escape(&self, byte: u8) -> Option<CharEscape> {
        if byte == b'/' {
            Some(CharEscape::Solidus)
        } else {
            CompactFormatter.char_escape(byte)
        }
    }
}
```

```rust
impl Formatter for HtmlSafeCompactFormatter {
    fn write_string_fragment<W: ?Sized + Write>(&mut self, w: &mut W, s: &str) -> io::Result<()> {
        for (i, split) in s.split('/').enumerate() {
            if i > 0 {
                w.write_all(b"\\/")?;
            }
            CompactFormatter.write_string_fragment(w, split)?;
        }
        Ok(())
    }
}
```

**Pull request closed without merging**
