### PR TITLE
allow reading from a slice that contains trailing bytes

### PR DESCRIPTION
**Pull request by oli-obk**
cc @vorner

### CODE REVIEW

**Comment by dtolnay** [comment]
Do you think we could generalize this to work with any JSON deserializer? The stream API is a lot nicer now with #205 than it used to be, and this seems like it would belong there.

Something like:

```rust
let mut stream = Deserializer::from_slice(data).into_iter::<T>();

/* deserialize some things */

let pos = stream.byte_pos();
```

**Comment by vorner** [comment]
Cool, that was fast :-). I think this is what I needed. Though, I'm not sure of the method name `try_from_slice` ‒ the difference from `from_slice` is that it returns the position as well, so the try seems bit confusing.

**Comment by oli-obk** [comment]
> Do you think we could generalize this to work with any JSON deserializer?

`from_iter` and `from_reader` would need to count bytes, too, but don't do it right now. So it would probably be slower then, and maybe impossible with `from_reader` entirely, since we might accidentally read part of the next value.

**Comment by oli-obk** [comment]
> so the try seems bit confusing.

a failure in that function doesn't mean an actual failure, it could just be that we're missing bytes

**Comment by vorner** [comment]
| a failure in that function doesn't mean an actual failure, it could just be that we're missing bytes

Thinking about this, is there any better way than to check for one of the `EOFWhileParsing` to see if it ended prematurely or if it was actually wrong?

**Comment by oli-obk** [comment]
> Thinking about this, is there any better way than to check for one of the EOFWhileParsing to see if it ended prematurely or if it was actually wrong?

Oh right. I actually wanted to change that function to return a `Result<Option<(T, usize)>>`, so you'd never get an `EOFWhileParsing`, since that's impossible in an infinite stream. Basically if you get a `None` and you have no more data, that's when you're in trouble ;)

**Comment by oli-obk** [comment]
> Do you think we could generalize this to work with any JSON deserializer? The stream API is a lot nicer now with #205 than it used to be, and this seems like it would belong there.

We could do that, but the ergonomics are weird, because you have to recreate the entire streamdeserializer when the previous one stops yielding elements.

The cleanest solution would probably be a specially tailored from_tokio_stream function in a tokio feature. It could internally buffer the slices until it's possible to read without triggering eof.

The "peek or null" methods make it kind of hard to distinguish between errors and end of stream, so these would have to be touched. Not sure how much they affect performance.

**Comment by dtolnay** [comment]
@vorner for your use case, if the input is `b"1" as &[u8]` would you expect it to return `Ok(None)` or `Ok(Some((Number(1), 1)))`? There isn't an immediate way to tell whether this will be followed by more digits in the same number.

**Comment by dtolnay** [comment]
I think we need this function to reject types other than array and object.

**Comment by vorner** [comment]
Hmm, number is stupid :-|. It can work with true/false/nil and with strings as well as arrays and objects. But I don't know about numbers.

Actually, all things that usually require this have objects or arrays, but I'm not sure what to do with this corner case. Maybe just return `Some(1)` and let the caller decide what to do (with some kind of warning in the documentation)?

**Comment by dtolnay** [comment]
Closing in favor of #183.

**Pull request closed without merging**
